# Generated by Django 5.2.10 on 2026-02-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_usercart_category_userorder_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
